{{- if .Values.backend.enabled }}
{{- if .Values.backend.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-uploads-pvc
  namespace: {{ .Values.namespace }}
  labels:
    app: backend
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.backend.persistence.size }}
  storageClassName: {{ .Values.backend.persistence.storageClass }}
{{- end }}
{{- end }}
