{{- if .Values.mysql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: {{ .Values.namespace }}
  labels:
    app: mysql
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
spec:
  selector:
    app: mysql
    release: {{ .Release.Name }}
  ports:
  - port: 3306
    targetPort: 3306
    protocol: TCP
  clusterIP: None
  type: ClusterIP
{{- end }}
