apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: research-journal
type: Opaque
data:
  # root (base64 encoded)
  mysql-root-password: cm9vdA==
  # research_journal_db (base64 encoded)
  mysql-database: cmVzZWFyY2hfam91cm5hbF9kYg==
